/* Generated By:JavaCC: Do not edit this line. FuncParserConstants.java */
public interface FuncParserConstants {

  int EOF = 0;
  int PLUS = 1;
  int MINUS = 2;
  int TIMES = 3;
  int DIVIDE = 4;
  int POWER = 5;
  int LPAR = 6;
  int RPAR = 7;
  int NUM = 8;
  int SIN = 9;
  int COS = 10;
  int TAN = 11;
  int LN = 12;
  int LOG = 13;
  int EULER = 14;
  int ABS = 15;
  int ID = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "<NUM>",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"ln\"",
    "\"log\"",
    "\"exp\"",
    "\"abs\"",
    "<ID>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
  };

}
